# Generated by Django 5.0.6 on 2024-06-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_cart_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
